orgs = [
    # "balena-fleetops",
    # "balena-io",
    # "balena-io-examples",
    # "balena-io-library",
    # "balena-io-modules",
    # "balena-io-playground",
    # "balena-os",
    "balenablocks",
    # "balenalabs",
    # "balenalabs-incubator",
    # "company-os",
    # "people-os",
    # "product-os",
    # "balenaltd",
]
